### PR TITLE
Temp values from 1w have not padding zeros.

### PR DESCRIPTION
**Pull request by Elektordi**
Prevents value freeze for temperatures below 10° (like now in France).

### CODE REVIEW

**Comment by turmoni** [comment]
Thanks, my only 1w temperature probe is indoors so it's always been >10. Do you know if it works with negative temperatures? I've been unable to verify that yet.

**Comment by Elektordi** [comment]
I'll see as soon as it's freezing outside. ;)

**Comment by Elektordi** [comment]
Just got one today:
```
fb ff 4b 46 7f ff 0c 10 06 : crc=06 YES
fb ff 4b 46 7f ff 0c 10 06 t=-312
```

And it seems to work:
```
onewire_temperature_c{location="exterieur"} -0.312
```

**Comment by turmoni** [comment]
Nice, thanks!

(Meanwhile I've been in sub-zero temperatures in two countries in the time it took your area to drop to the negatives, I have clearly made some bad decisions somewhere.)

**Pull request merged**
